# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HYDA
                                 A QGIS plugin
 Hydrological Delimitation Assistant
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-20
        copyright            : (C) 2025 by eduardo a
        email                : eduardoaqgis@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HYDA class from file HYDA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .HYDA import HYDA
    return HYDA(iface)
